server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Booker-nyximos/cloud-config.git
          username: ${vault.git.id}
          password: ${vault.git.password}
          default-label: develop
        vault:
          host: 127.0.0.1
          port: 8200
          scheme: http
          uri: http://127.0.0.1:8200
          token:
          authentication: token
          kv:
            version: 2
            backend: booker
            profiles: develop
