server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Booker-nyximos/cloud-config.git
          username: nyximos
          password:
          default-label: develop
        vault:
          host: 127.0.0.1
          port: 8200
          kv-version: 2
          backend: booker
          authentication: token
          token:
